//
// Body.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Body

import Vapor


public final class Body: Content {

    public var username: String?

    public init(username: String?) { 
        self.username = username
    }
}
