//
// Capability.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Capability

import Vapor


public final class Capability: Content {

    public var `id`: Int64?
    public var name: String?

    public init(`id`: Int64?, name: String?) { 
        self.`id` = `id`
        self.name = name
    }
}
