//
// Capabilities.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Capabilities

import Vapor

public typealias Capabilities = [Capability]