//
// GameObjects.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.GameObjects

import Vapor

public typealias GameObjects = [GameObject]