//
// Game.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Game

import Vapor


public final class Game: Content {

    public var `id`: Int64?
    public var gameObjects: GameObjects?

    public init(`id`: Int64?, gameObjects: GameObjects?) { 
        self.`id` = `id`
        self.gameObjects = gameObjects
    }
}
