//
// User.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.User

import Vapor


public final class User: Content {

    public var `id`: Int64?
    public var username: String?
    public var password: String?

    public init(`id`: Int64?, username: String?, password: String?) { 
        self.`id` = `id`
        self.username = username
        self.password = password
    }
}
