name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -workspace SolidCourseFramework.xcworkspace -scheme SolidCourseFramework
    - name: Run tests
      run: xcodebuild -workspace SolidCourseFramework.xcworkspace -scheme SolidCourseFrameworkTests test
