//
// InterpretCommandAPIModel.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.InterpretCommandAPIModel

import Vapor


public final class InterpretCommandAPIModel: Content {

    public var objectId: Int64?
    public var commandId: Int64?
    public var args: String?

    public init(objectId: Int64?, commandId: Int64?, args: String?) { 
        self.objectId = objectId
        self.commandId = commandId
        self.args = args
    }
}
