//
// JwtTokenAPIModel.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.JwtTokenAPIModel

import Vapor


public final class JwtTokenAPIModel: Content {

    public var token: String?

    public init(token: String?) { 
        self.token = token
    }
}
