//
// ObjectsAPIModel.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ObjectsAPIModel

import Vapor

public typealias ObjectsAPIModel = [ObjectAPIModel]