//
// UsersAPIModel.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.UsersAPIModel

import Vapor

public typealias UsersAPIModel = [UserAPIModel]