//
// UserIdsAPIModel.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.UserIdsAPIModel

import Vapor

public typealias UserIdsAPIModel = [Int64]