//
// UserAPIModel.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.UserAPIModel

import Vapor


public final class UserAPIModel: Content {

    public var id: Int64?
    public var username: String?
    public var password: String?

    public init(id: Int64?, username: String?, password: String?) { 
        self.id = id
        self.username = username
        self.password = password
    }
}
